# Copyright (c) 2026 Orders of Magnitude LLC
# Licensed under the OOM Commercial License v1.0
# See LICENSE.md in the repository root or ofmagnitude.com

"""57 new categories for the 100-problem / 2000-candidate screen."""

EXTRA_CATEGORY_FILTERS = {
    "battery_anode_sodium": {"elements_must_include_any": ["Na","Sn","Sb","Ti","P","C","Bi"], "band_gap_max": 2.0, "formation_energy_max": -0.1},
    "battery_cathode_sodium": {"elements_must_include_any": ["Na","Fe","Mn","V","Ti","P","O"], "band_gap_min": 0.5, "formation_energy_max": -0.5},
    "flow_battery_membrane": {"elements_must_include_any": ["S","F","C","O","N"], "band_gap_min": 1.0},
    "redox_flow_electrolyte": {"elements_must_include_any": ["V","Fe","Cr","Zn","Br","S","Mn"], "band_gap_max": 1.0, "formation_energy_max": -0.3},
    "thermoelectric_low_grade_heat": {"elements_must_include_any": ["Bi","Te","Sb","Se","Pb","Cu","Ag"], "band_gap_min": 0.3, "band_gap_max": 1.5},
    "piezoelectric_energy_harvesting": {"elements_must_include_any": ["K","Na","Nb","Bi","Ti","Ba","Zn","Zr"], "band_gap_min": 1.0, "band_gap_max": 5.0},
    "triboelectric_nanogenerator": {"elements_must_include_any": ["Si","O","C","F","Al","Ti","N"], "band_gap_min": 2.0},
    "solar_thermal_storage": {"elements_must_include_any": ["Na","K","Li","Ca","Mg","Al","Si","O"], "band_gap_min": 3.0, "formation_energy_max": -1.0},
    "molten_salt_thermal": {"elements_must_include_any": ["Na","K","Li","Ca","Mg","Cl","F"], "band_gap_min": 3.0},
    "fuel_cell_electrolyte": {"elements_must_include_any": ["Zr","Ce","Ba","La","Gd","O","H"], "band_gap_min": 2.0, "formation_energy_max": -0.5},
    "fuel_cell_anode": {"elements_must_include_any": ["Ni","Cu","Co","Fe","W","Mo","Cr"], "band_gap_max": 0.5, "formation_energy_max": -0.2},
    "fuel_cell_cathode": {"elements_must_include_any": ["La","Sr","Co","Fe","Mn","Cr","O"], "band_gap_max": 1.0, "formation_energy_max": -0.5},
    "supercapacitor_electrode": {"elements_must_include_any": ["C","Mn","Fe","Ru","Co","Ni","V","O"], "band_gap_max": 2.0},
    "battery_solid_interface": {"elements_must_include_any": ["Li","P","S","O","Ge","Sn","Cl","Br"], "band_gap_min": 1.0, "band_gap_max": 6.0, "formation_energy_max": -0.5},
    "grid_scale_storage_iron": {"elements_must_include_any": ["Fe","V","Cr","Mn","Ti","O","S"], "band_gap_max": 1.0, "formation_energy_max": -0.3},
    "desalination_reverse_osmosis": {"elements_must_include_any": ["Si","Al","Ti","Zr","C","O","N"], "band_gap_min": 3.0},
    "desalination_solar_still": {"elements_must_include_any": ["Al","Cu","C","Ti","Si","O","N"], "band_gap_min": 1.0},
    "arsenic_removal": {"elements_must_include_any": ["Fe","Ti","Al","Mn","Zr","Ce","Cu","O"], "band_gap_min": 1.0},
    "nitrate_removal": {"elements_must_include_any": ["Fe","Al","Ti","Zr","Mn","C","O"], "band_gap_min": 1.0},
    "pharmaceutical_water_filter": {"elements_must_include_any": ["Ti","Al","Fe","C","Si","O","Mn"], "band_gap_min": 2.0},
    "microplastic_filter": {"elements_must_include_any": ["Fe","Ti","Al","C","Si","Mn","O"], "band_gap_min": 1.0},
    "oil_spill_sorbent": {"elements_must_include_any": ["C","Si","O","Al","Fe","Ti","Mg"], "band_gap_min": 1.0},
    "acid_mine_drainage": {"elements_must_include_any": ["Fe","Al","Ca","Mg","Mn","Zn","Cu","O","S"], "band_gap_min": 0.5},
    "radioactive_water_treatment": {"elements_must_include_any": ["Ti","Zr","Fe","Al","Si","Mn","O","P"], "band_gap_min": 1.0},
    "ammonia_recovery_wastewater": {"elements_must_include_any": ["Mg","Ca","Al","Fe","P","O","N","K"], "band_gap_min": 1.0},
    "slow_release_fertilizer": {"elements_must_include_any": ["N","P","K","Ca","Mg","Fe","O","S"], "band_gap_min": 2.0},
    "pesticide_degradation": {"elements_must_include_any": ["Ti","Fe","Mn","Zn","Cu","O","C"], "band_gap_min": 1.0, "band_gap_max": 4.0},
    "food_packaging_biodegradable": {"elements_must_include_any": ["C","O","H","N","Mg","Ca","Fe"], "band_gap_min": 3.0},
    "silage_preservative": {"elements_must_include_any": ["C","O","N","Na","K","Ca","S"], "band_gap_min": 3.0},
    "soil_remediation_heavy_metal": {"elements_must_include_any": ["Fe","Al","Ca","Mg","Mn","Si","O","P"], "band_gap_min": 1.0},
    "drought_resistant_hydrogel": {"elements_must_include_any": ["C","O","H","N","Na","K","Al","Si"], "band_gap_min": 3.0},
    "seed_coating_material": {"elements_must_include_any": ["C","O","N","P","K","Ca","Fe","Zn"], "band_gap_min": 2.0},
    "compost_accelerator": {"elements_must_include_any": ["Mn","Fe","Cu","Zn","C","O","N"], "band_gap_max": 2.0},
    "bone_implant_bioceramic": {"elements_must_include_any": ["Ca","P","Si","Mg","O","Zn","Sr"], "band_gap_min": 2.0, "formation_energy_max": -0.5},
    "dental_filling_material": {"elements_must_include_any": ["Ag","Sn","Cu","Zn","Bi","Si","Al","O"], "band_gap_max": 3.0},
    "wound_dressing_antimicrobial": {"elements_must_include_any": ["Ag","Zn","Cu","C","O","N","Ti"], "band_gap_min": 1.0},
    "drug_delivery_mesoporous": {"elements_must_include_any": ["Si","O","C","Ti","Fe","Ca","P"], "band_gap_min": 2.0},
    "mri_contrast_agent": {"elements_must_include_any": ["Gd","Fe","Mn","O","F","C","N"], "band_gap_min": 0.0},
    "prosthetic_coating": {"elements_must_include_any": ["Ti","Al","V","Ta","Nb","O","N","C"], "band_gap_min": 2.0},
    "biosensor_electrode": {"elements_must_include_any": ["Au","Pt","C","Ag","Cu","Zn","O","N"], "band_gap_max": 2.0},
    "uv_blocking_material": {"elements_must_include_any": ["Ti","Zn","Ce","Al","Si","O","Fe"], "band_gap_min": 3.0},
    "self_healing_concrete": {"elements_must_include_any": ["Ca","Si","Al","Fe","O","S","C","Mg"], "band_gap_min": 2.0, "formation_energy_max": -0.5},
    "fire_resistant_cladding": {"elements_must_include_any": ["Al","Mg","Si","Ca","C","O","B","Ti"], "band_gap_min": 3.0},
    "thermal_insulation_aerogel": {"elements_must_include_any": ["Si","C","O","Al","Ti","Zr","B","N"], "band_gap_min": 3.0},
    "smart_window_electrochromic": {"elements_must_include_any": ["W","Mo","V","Nb","Ta","O","Li","H"], "band_gap_min": 1.0, "band_gap_max": 4.0},
    "steel_rebar_anticorrosion": {"elements_must_include_any": ["Zn","Al","Mg","Cr","Ni","Si","O","C"], "band_gap_min": 1.0},
    "bridge_deicing_coating": {"elements_must_include_any": ["C","O","Si","Ti","Al","N","F"], "band_gap_min": 2.0},
    "pipe_linings_leadfree": {"elements_must_include_any": ["Fe","Cr","Ni","Al","Si","O","C","Zn"], "band_gap_min": 1.0},
    "lightweight_concrete_aggregate": {"elements_must_include_any": ["Si","Al","Ca","Fe","O","C","Mg"], "band_gap_min": 2.0},
    "cutting_tool_coating": {"elements_must_include_any": ["Ti","Cr","Al","N","C","Si","B","W"], "band_gap_min": 1.0, "formation_energy_max": -0.5},
    "bearing_material_lowfriction": {"elements_must_include_any": ["Cu","Sn","Pb","Sb","Al","Fe","C","Si"], "band_gap_max": 2.0},
    "mold_release_coating": {"elements_must_include_any": ["Si","C","O","F","B","N","Ti","Al"], "band_gap_min": 3.0},
    "heat_sink_composite": {"elements_must_include_any": ["Al","Cu","Si","C","O","N","Ti","Ag"], "band_gap_min": 1.0},
    "solder_leadfree": {"elements_must_include_any": ["Sn","Ag","Cu","Bi","Zn","Sb","Ni"], "band_gap_max": 1.0},
    "brazing_filler": {"elements_must_include_any": ["Ag","Cu","Zn","Sn","Al","Si","Ni","P"], "band_gap_max": 1.0},
    "catalyst_petroleum_cracking": {"elements_must_include_any": ["Al","Si","O","Ti","Fe","Ce","La","Zr"], "band_gap_min": 2.0},
    "catalyst_ethylene_production": {"elements_must_include_any": ["Cr","Ni","Mo","Fe","Co","O","Al","Si"], "band_gap_max": 2.0, "formation_energy_max": -0.3},
}

EXTRA_CATEGORY_NOTES = {
    "battery_anode_sodium": "Na-ion battery anode — post-Li energy storage. NEEDS: Carbonization or alloy synthesis. OUTPUT: Na-ion anode. DEPLOY: Grid Na-ion batteries. CONJECTURE pending phonon confirmation.",
    "battery_cathode_sodium": "Na-ion cathode — earth-abundant storage. NEEDS: Solid-state synthesis. OUTPUT: Na-ion cathode. DEPLOY: Stationary storage. CONJECTURE pending phonon confirmation.",
    "flow_battery_membrane": "Ion-exchange membrane for flow batteries. NEEDS: Polymer or ceramic membrane. OUTPUT: Selective ion transport. DEPLOY: Grid flow batteries. CONJECTURE pending phonon confirmation.",
    "redox_flow_electrolyte": "Redox-active electrolyte. NEEDS: Electrolyte formulation. OUTPUT: Solution energy storage. DEPLOY: Long-duration grid storage. CONJECTURE pending phonon confirmation.",
    "thermoelectric_low_grade_heat": "Thermoelectric for waste heat <200C. NEEDS: Nanostructuring. OUTPUT: Electricity from waste heat. DEPLOY: Factory heat recovery. CONJECTURE pending phonon confirmation.",
    "piezoelectric_energy_harvesting": "Lead-free piezoelectric harvester. NEEDS: Ceramic sintering. OUTPUT: Mechanical-to-electrical. DEPLOY: IoT sensors, wearables. CONJECTURE pending phonon confirmation.",
    "triboelectric_nanogenerator": "Triboelectric energy harvester. NEEDS: Thin-film fabrication. OUTPUT: Electricity from contact. DEPLOY: Self-powered sensors. CONJECTURE pending phonon confirmation.",
    "solar_thermal_storage": "Sensible heat storage for CSP. NEEDS: High-T stable media. OUTPUT: Thermal storage 600-1000C. DEPLOY: CSP plants. CONJECTURE pending phonon confirmation.",
    "molten_salt_thermal": "Molten salt heat transfer fluid. NEEDS: Corrosion-resistant containment. OUTPUT: Heat transfer + storage. DEPLOY: Solar thermal. CONJECTURE pending phonon confirmation.",
    "fuel_cell_electrolyte": "Solid oxide or proton electrolyte. NEEDS: High-T sintering. OUTPUT: Ion-conducting membrane. DEPLOY: Stationary fuel cells. CONJECTURE pending phonon confirmation.",
    "fuel_cell_anode": "Non-precious anode catalyst. NEEDS: Composite electrode. OUTPUT: H2 oxidation. DEPLOY: SOFC/PEMFC anodes. CONJECTURE pending phonon confirmation.",
    "fuel_cell_cathode": "Perovskite or spinel cathode. NEEDS: Solid-state synthesis. OUTPUT: O2 reduction. DEPLOY: SOFC cathodes. CONJECTURE pending phonon confirmation.",
    "supercapacitor_electrode": "Pseudocapacitive electrode. NEEDS: Nanostructure. OUTPUT: High-power storage. DEPLOY: Peak power, braking. CONJECTURE pending phonon confirmation.",
    "battery_solid_interface": "Solid electrolyte interface. NEEDS: Thin-film or pellet. OUTPUT: Dendrite-free SE. DEPLOY: Solid-state batteries. CONJECTURE pending phonon confirmation.",
    "grid_scale_storage_iron": "Iron-based grid storage. NEEDS: Electrode fabrication. OUTPUT: Low-cost long-duration. DEPLOY: Iron-air/flow. CONJECTURE pending phonon confirmation.",
    "desalination_reverse_osmosis": "High-flux RO membrane. NEEDS: Thin-film composite. OUTPUT: Salt rejection >99%. DEPLOY: Municipal desalination. CONJECTURE pending phonon confirmation.",
    "desalination_solar_still": "Solar-thermal desalination. NEEDS: Solar absorber. OUTPUT: Evaporation purification. DEPLOY: Off-grid coastal. CONJECTURE pending phonon confirmation.",
    "arsenic_removal": "Arsenic adsorbent. NEEDS: Granular media. OUTPUT: As <10ppb. DEPLOY: Well water treatment. CONJECTURE pending phonon confirmation.",
    "nitrate_removal": "Nitrate adsorbent/catalyst. NEEDS: Granular media. OUTPUT: NO3- removal. DEPLOY: Agricultural runoff. CONJECTURE pending phonon confirmation.",
    "pharmaceutical_water_filter": "Pharma removal media. NEEDS: Photocatalyst. OUTPUT: Pharma degradation. DEPLOY: WWTP. CONJECTURE pending phonon confirmation.",
    "microplastic_filter": "Microplastic capture. NEEDS: Membrane. OUTPUT: >90% removal. DEPLOY: WWTP tertiary. CONJECTURE pending phonon confirmation.",
    "oil_spill_sorbent": "Hydrophobic oleophilic sorbent. NEEDS: Aerogel/foam. OUTPUT: Oil absorption >50x. DEPLOY: Marine spill. CONJECTURE pending phonon confirmation.",
    "acid_mine_drainage": "AMD treatment media. NEEDS: Passive/active media. OUTPUT: pH + metal removal. DEPLOY: Mining remediation. CONJECTURE pending phonon confirmation.",
    "radioactive_water_treatment": "Radionuclide removal. NEEDS: Ion exchanger. OUTPUT: Cs/Sr/U removal. DEPLOY: Nuclear cleanup. CONJECTURE pending phonon confirmation.",
    "ammonia_recovery_wastewater": "NH3 recovery for fertilizer. NEEDS: Stripping media. OUTPUT: NH3 recovery. DEPLOY: Municipal WWTP. CONJECTURE pending phonon confirmation.",
    "slow_release_fertilizer": "Controlled-release fertilizer. NEEDS: Coating. OUTPUT: 3-6 month release. DEPLOY: Precision ag. CONJECTURE pending phonon confirmation.",
    "pesticide_degradation": "Pesticide breakdown catalyst. NEEDS: Photocatalyst. OUTPUT: Pesticide mineralization. DEPLOY: Runoff treatment. CONJECTURE pending phonon confirmation.",
    "food_packaging_biodegradable": "Biodegradable packaging. NEEDS: Biopolymer. OUTPUT: Shelf-life + compostability. DEPLOY: Food industry. CONJECTURE pending phonon confirmation.",
    "silage_preservative": "Silage fermentation additive. NEEDS: Additive. OUTPUT: Reduced spoilage. DEPLOY: Livestock farming. CONJECTURE pending phonon confirmation.",
    "soil_remediation_heavy_metal": "Soil metal immobilization. NEEDS: Soil amendment. OUTPUT: Reduced bioavailability. DEPLOY: Brownfield. CONJECTURE pending phonon confirmation.",
    "drought_resistant_hydrogel": "Soil water retention. NEEDS: Polymer. OUTPUT: 200-400x absorption. DEPLOY: Dryland farming. CONJECTURE pending phonon confirmation.",
    "seed_coating_material": "Seed protective coating. NEEDS: Biopolymer + nutrients. OUTPUT: Better germination. DEPLOY: Commercial ag. CONJECTURE pending phonon confirmation.",
    "compost_accelerator": "Composting catalyst. NEEDS: Mineral additive. OUTPUT: Faster composting. DEPLOY: Municipal compost. CONJECTURE pending phonon confirmation.",
    "bone_implant_bioceramic": "Bioactive bone repair. NEEDS: Sintering/sol-gel. OUTPUT: Osseointegration. DEPLOY: Orthopedic/dental. CONJECTURE pending phonon confirmation.",
    "dental_filling_material": "Hg-free dental restorative. NEEDS: Composite/alloy. OUTPUT: Durable filling. DEPLOY: Dental clinics. CONJECTURE pending phonon confirmation.",
    "wound_dressing_antimicrobial": "Antimicrobial dressing. NEEDS: Fiber/hydrogel. OUTPUT: Infection prevention. DEPLOY: Clinical medicine. CONJECTURE pending phonon confirmation.",
    "drug_delivery_mesoporous": "Mesoporous drug carrier. NEEDS: Template synthesis. OUTPUT: Sustained release. DEPLOY: Pharma. CONJECTURE pending phonon confirmation.",
    "mri_contrast_agent": "Gd-free MRI contrast. NEEDS: Nanoparticle. OUTPUT: T1/T2 contrast. DEPLOY: Medical imaging. CONJECTURE pending phonon confirmation.",
    "prosthetic_coating": "Biocompatible implant coating. NEEDS: Surface treatment. OUTPUT: Wear resistance. DEPLOY: Joint replacement. CONJECTURE pending phonon confirmation.",
    "biosensor_electrode": "Biosensor electrode. NEEDS: Nanostructure. OUTPUT: Biomolecule detection. DEPLOY: Point-of-care. CONJECTURE pending phonon confirmation.",
    "uv_blocking_material": "UV-blocking coating. NEEDS: Nanoparticle dispersion. OUTPUT: >99% UV block. DEPLOY: Sunscreen, windows. CONJECTURE pending phonon confirmation.",
    "self_healing_concrete": "Self-healing concrete additive. NEEDS: Bacterial/crystalline. OUTPUT: Autonomous crack repair. DEPLOY: Infrastructure. CONJECTURE pending phonon confirmation.",
    "fire_resistant_cladding": "Fire-resistant cladding. NEEDS: Panel fabrication. OUTPUT: Fire rating A1. DEPLOY: Building facades. CONJECTURE pending phonon confirmation.",
    "thermal_insulation_aerogel": "Ultra-low k insulation. NEEDS: Sol-gel. OUTPUT: k < 0.03 W/mK. DEPLOY: Building, aerospace. CONJECTURE pending phonon confirmation.",
    "smart_window_electrochromic": "Electrochromic window. NEEDS: Thin-film. OUTPUT: Dynamic solar control. DEPLOY: Building, automotive. CONJECTURE pending phonon confirmation.",
    "steel_rebar_anticorrosion": "Rebar corrosion protection. NEEDS: Coating. OUTPUT: 50+ year life. DEPLOY: Infrastructure. CONJECTURE pending phonon confirmation.",
    "bridge_deicing_coating": "Anti-icing coating. NEEDS: Surface treatment. OUTPUT: Passive deicing. DEPLOY: Bridge decks. CONJECTURE pending phonon confirmation.",
    "pipe_linings_leadfree": "Lead-free pipe lining. NEEDS: Epoxy/polymer. OUTPUT: Pb-free water. DEPLOY: Water systems. CONJECTURE pending phonon confirmation.",
    "lightweight_concrete_aggregate": "Lightweight aggregate. NEEDS: Sintered clay. OUTPUT: 30-50% weight reduction. DEPLOY: High-rise. CONJECTURE pending phonon confirmation.",
    "cutting_tool_coating": "Wear-resistant tool coating. NEEDS: PVD/CVD. OUTPUT: 3-10x tool life. DEPLOY: Machining. CONJECTURE pending phonon confirmation.",
    "bearing_material_lowfriction": "Low-friction bearing. NEEDS: Casting/sintering. OUTPUT: Reduced friction. DEPLOY: Machinery. CONJECTURE pending phonon confirmation.",
    "mold_release_coating": "Non-stick mold release. NEEDS: Spray/CVD. OUTPUT: Reduced defects. DEPLOY: Manufacturing. CONJECTURE pending phonon confirmation.",
    "heat_sink_composite": "High-k heat sink. NEEDS: Composite. OUTPUT: Thermal management. DEPLOY: Electronics. CONJECTURE pending phonon confirmation.",
    "solder_leadfree": "Pb-free solder. NEEDS: Alloy casting. OUTPUT: Pb-free interconnect. DEPLOY: Electronics. CONJECTURE pending phonon confirmation.",
    "brazing_filler": "Brazing filler metal. NEEDS: Alloy. OUTPUT: High-strength joint. DEPLOY: HVAC, automotive. CONJECTURE pending phonon confirmation.",
    "catalyst_petroleum_cracking": "Zeolite cracking catalyst. NEEDS: Hydrothermal. OUTPUT: Improved yield. DEPLOY: Refinery FCC. CONJECTURE pending phonon confirmation.",
    "catalyst_ethylene_production": "Ethylene catalyst. NEEDS: Impregnation. OUTPUT: Selective dehydrogenation. DEPLOY: Petrochemical. CONJECTURE pending phonon confirmation.",
}
